#!/bin/bash

echo "🌐 Setting up public access for WebRTC signaling server..."
echo ""
echo "Option 1: Use ngrok (requires account)"
echo "  1. Install: brew install ngrok/ngrok/ngrok"
echo "  2. Sign up: https://ngrok.com/"
echo "  3. Run: ngrok http 8080"
echo "  4. Copy the https URL and update signalingService.ts"
echo ""
echo "Option 2: Use Cloudflare Tunnel (free, no signup for localhost)"
echo "  1. Install: brew install cloudflare/cloudflare/cloudflared"
echo "  2. Run: cloudflared tunnel --url http://localhost:8080"
echo "  3. Copy the https URL and update signalingService.ts"
echo ""
echo "Option 3: Use localtunnel (easiest, no signup)"
echo "  1. Install: npm install -g localtunnel"
echo "  2. Run: lt --port 8080"
echo "  3. Copy the https URL and update signalingService.ts"
echo ""
echo "After getting a public URL, update: services/signalingService.ts"
echo "Change: ws://localhost:8080"
echo "To: wss://your-public-url (use wss:// for secure WebSocket)"
