
import React, { useState, useEffect, useCallback } from 'react';
import { generateSessionReport } from '../services/geminiService';
import { SessionReport } from '../types';

interface ReportViewProps {
  transcript: string;
  onStartNewSession: () => void;
  onNavigateToProfile: () => void;
  gamificationData: {
      sessionCount: number;
      streak: number;
  }
}

const LoadingSpinner: React.FC = () => (
    <div className="flex justify-center items-center h-full">
        <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-brand-primary"></div>
    </div>
);

const ReportCard: React.FC<{ title: string; children: React.ReactNode; icon: React.ReactNode }> = ({ title, children, icon }) => (
    <div className="bg-brand-gray-800 rounded-lg p-6 shadow-lg">
        <div className="flex items-center mb-4">
            <div className="mr-3 text-brand-secondary">{icon}</div>
            <h3 className="text-lg font-semibold text-brand-light">{title}</h3>
        </div>
        <div className="text-brand-gray-300 space-y-2">{children}</div>
    </div>
);

const AchievementBadge: React.FC<{ icon: React.ReactNode; label: string; achieved: boolean }> = ({ icon, label, achieved }) => (
    <div className={`flex items-center p-3 rounded-lg transition-all ${achieved ? 'bg-brand-secondary/20 text-brand-secondary' : 'bg-brand-gray-700 text-brand-gray-400'}`}>
        <div className={`mr-3 ${achieved ? 'opacity-100' : 'opacity-50'}`}>{icon}</div>
        <span className={`font-medium ${achieved ? 'opacity-100' : 'opacity-50'}`}>{label}</span>
    </div>
);

const ReportView: React.FC<ReportViewProps> = ({ transcript, gamificationData, onStartNewSession, onNavigateToProfile }) => {
  const [report, setReport] = useState<SessionReport | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchReport = useCallback(async () => {
    if (!transcript) {
        setError("No transcript available to generate a report.");
        setIsLoading(false);
        return;
    };
    setIsLoading(true);
    setError(null);
    try {
      const generatedReport = await generateSessionReport(transcript);
      setReport(generatedReport);
    } catch (err: any) {
      console.error('Report generation error:', err);
      let errorMessage = 'Failed to generate session report. ';
      
      if (err?.message) {
        if (err.message.includes('API') || err.message.includes('key')) {
          errorMessage += 'API key error. Please check your environment variables.';
        } else if (err.message.includes('quota') || err.message.includes('limit')) {
          errorMessage += 'API quota exceeded. Please try again later.';
        } else if (err.message.includes('403') || err.message.includes('PERMISSION_DENIED')) {
          errorMessage += 'API key invalid or revoked. Please check your API key settings.';
        } else {
          errorMessage += err.message;
        }
      } else {
        errorMessage += 'The AI may be experiencing high load. Please try again.';
      }
      
      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  }, [transcript]);

  useEffect(() => {
    fetchReport();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [transcript]);

  const downloadPDF = useCallback(() => {
    if (!report) return;
    
    // Create HTML content for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>Peer Session Report</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
            h1 { color: #6366f1; border-bottom: 3px solid #6366f1; padding-bottom: 10px; }
            h2 { color: #4f46e5; margin-top: 30px; }
            h3 { color: #6366f1; margin-top: 20px; }
            .section { margin-bottom: 30px; }
            .talk-time { display: flex; gap: 20px; margin: 15px 0; }
            .peer-box { flex: 1; padding: 15px; background: #f3f4f6; border-radius: 8px; }
            .progress-bar { height: 20px; background: #e5e7eb; border-radius: 10px; overflow: hidden; margin-top: 10px; }
            .progress-fill { height: 100%; background: #6366f1; }
            ul { margin: 10px 0; padding-left: 20px; }
            li { margin: 5px 0; }
            .action-item { padding: 10px; background: #f9fafb; border-left: 3px solid #6366f1; margin: 5px 0; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center; color: #6b7280; }
          </style>
        </head>
        <body>
          <h1>Peer Accountability Session Report</h1>
          <p><em>Generated by Kelly AI Coach</em></p>
          
          <div class="section">
            <h2>Session Summary</h2>
            <p>${report.summary}</p>
          </div>
          
          <div class="section">
            <h2>Talk Time Distribution</h2>
            <div class="talk-time">
              <div class="peer-box">
                <strong>Peer A: ${report.talkTime.peerA.toFixed(1)}%</strong>
                <div class="progress-bar">
                  <div class="progress-fill" style="width: ${report.talkTime.peerA}%"></div>
                </div>
              </div>
              <div class="peer-box">
                <strong>Peer B: ${report.talkTime.peerB.toFixed(1)}%</strong>
                <div class="progress-bar">
                  <div class="progress-fill" style="width: ${report.talkTime.peerB}%"></div>
                </div>
              </div>
            </div>
          </div>
          
          <div class="section">
            <h2>Key Highlights</h2>
            <h3>Peer A's Highlights</h3>
            <ul>
              ${report.highlights.peerA.map(h => `<li>${h}</li>`).join('')}
            </ul>
            <h3>Peer B's Highlights</h3>
            <ul>
              ${report.highlights.peerB.map(h => `<li>${h}</li>`).join('')}
            </ul>
          </div>
          
          <div class="section">
            <h2>Action Items</h2>
            ${report.actionItems.length > 0 
              ? report.actionItems.map(item => `
                  <div class="action-item">
                    <strong>${item.owner}:</strong> ${item.action}
                  </div>
                `).join('')
              : '<p>No specific action items were identified.</p>'
            }
          </div>
          
          <div class="section">
            <h2>Mood & Engagement</h2>
            <p>${report.moodAnalysis}</p>
          </div>
          
          <div class="section">
            <h2>Progress Statistics</h2>
            <p><strong>Total Sessions:</strong> ${gamificationData.sessionCount}</p>
            <p><strong>Current Streak:</strong> ${gamificationData.streak} days</p>
          </div>
          
          <div class="footer">
            <p>Report generated on ${new Date().toLocaleDateString()}</p>
            <p>© Volley Peer Accountability Platform</p>
          </div>
        </body>
      </html>
    `;
    
    // Create blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `peer-session-report-${new Date().toISOString().split('T')[0]}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    // Also open print dialog for PDF conversion
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 250);
    }
  }, [report, gamificationData]);

  if (isLoading) {
    return (
        <div className="min-h-screen flex flex-col justify-center items-center bg-brand-dark p-4">
            <h2 className="text-2xl font-bold mb-4 text-brand-light">Generating Your Session Report...</h2>
            <p className="text-brand-gray-400 mb-8">Kelly is analyzing your conversation for key insights.</p>
            <LoadingSpinner />
        </div>
    );
  }

  if (error || !report) {
    return (
        <div className="min-h-screen flex flex-col justify-center items-center bg-brand-dark p-4 text-center">
            <h2 className="text-2xl font-bold text-red-500 mb-4">An Error Occurred</h2>
            <p className="text-brand-gray-300 mb-8">{error}</p>
            <div className="flex gap-4">
                <button
                    onClick={fetchReport}
                    className="bg-brand-secondary text-white font-semibold px-6 py-3 rounded-full hover:bg-green-500 transition-colors"
                >
                    Retry Report Generation
                </button>
                <button
                    onClick={onStartNewSession}
                    className="bg-brand-primary text-white font-semibold px-6 py-3 rounded-full hover:bg-indigo-500 transition-colors"
                >
                    Start a New Session
                </button>
            </div>
        </div>
    );
  }

  const peerATalkPercentage = report.talkTime.peerA || 50;
  const peerBTalkPercentage = report.talkTime.peerB || 50;

  return (
    <div className="max-w-7xl mx-auto p-4 sm:p-6 lg:p-8">
      <header className="mb-8 flex flex-col md:flex-row justify-between items-center">
        <div>
            <h1 className="text-3xl font-bold text-white">Peer Session Intelligence Report</h1>
            <p className="text-brand-gray-400 mt-1">Here's a summary of your coaching session, moderated by Kelly.</p>
        </div>
        <div className="mt-4 md:mt-0 flex items-center gap-4">
            <button
                onClick={downloadPDF}
                className="bg-brand-secondary text-white font-semibold px-6 py-3 rounded-full hover:bg-green-500 transition-colors flex items-center gap-2"
            >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Download PDF
            </button>
             <button
                onClick={onStartNewSession}
                className="bg-brand-primary text-white font-semibold px-6 py-3 rounded-full hover:bg-indigo-500 transition-colors"
            >
                Start New Session
            </button>
            <button onClick={onNavigateToProfile} className="p-3 bg-brand-gray-700 rounded-full hover:bg-brand-gray-600 transition-colors" aria-label="View Profile">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                </svg>
            </button>
        </div>
      </header>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
            <ReportCard title="Session Summary" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h7" /></svg>}>
                <p>{report.summary}</p>
            </ReportCard>
            <ReportCard title="Action Items" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" /></svg>}>
                {report.actionItems.length > 0 ? (
                    <ul className="list-disc pl-5 space-y-2">
                        {report.actionItems.map((item, i) => (
                            <li key={i}><strong>{item.owner}:</strong> {item.action}</li>
                        ))}
                    </ul>
                ) : <p>No specific action items were identified.</p>}
            </ReportCard>
             <ReportCard title="Key Highlights" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" /></svg>}>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <h4 className="font-semibold text-brand-light mb-2">Peer A's Highlights</h4>
                        <ul className="list-disc pl-5 space-y-1">
                            {report.highlights.peerA.map((item, i) => <li key={i}>{item}</li>)}
                        </ul>
                    </div>
                    <div>
                        <h4 className="font-semibold text-brand-light mb-2">Peer B's Highlights</h4>
                         <ul className="list-disc pl-5 space-y-1">
                            {report.highlights.peerB.map((item, i) => <li key={i}>{item}</li>)}
                        </ul>
                    </div>
                </div>
            </ReportCard>
            <ReportCard title="Sentiment Analysis" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>}>
                <p className="mb-4 text-brand-gray-300"><strong>Overall:</strong> {report.sentimentAnalysis?.overall || report.moodAnalysis}</p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-3">
                        <h4 className="font-semibold text-brand-light">Peer A</h4>
                        <div className="flex items-center gap-2 mb-2">
                            <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                                report.sentimentAnalysis?.peerA?.sentiment === 'positive' ? 'bg-green-500/20 text-green-400' :
                                report.sentimentAnalysis?.peerA?.sentiment === 'negative' ? 'bg-red-500/20 text-red-400' :
                                'bg-gray-500/20 text-gray-400'
                            }`}>
                                {report.sentimentAnalysis?.peerA?.sentiment || 'neutral'}
                            </span>
                            <span className="text-sm text-brand-gray-400">{report.sentimentAnalysis?.peerA?.emotionalState || 'N/A'}</span>
                        </div>
                        {report.sentimentAnalysis?.peerA?.whatWentWell && report.sentimentAnalysis.peerA.whatWentWell.length > 0 && (
                            <div>
                                <p className="text-sm font-semibold text-green-400 mb-1">✓ What Went Well:</p>
                                <ul className="list-disc pl-5 space-y-1 text-sm">
                                    {report.sentimentAnalysis.peerA.whatWentWell.map((item, i) => <li key={i}>{item}</li>)}
                                </ul>
                            </div>
                        )}
                        {report.sentimentAnalysis?.peerA?.whatWentWrong && report.sentimentAnalysis.peerA.whatWentWrong.length > 0 && (
                            <div>
                                <p className="text-sm font-semibold text-orange-400 mb-1">⚠ Areas for Improvement:</p>
                                <ul className="list-disc pl-5 space-y-1 text-sm">
                                    {report.sentimentAnalysis.peerA.whatWentWrong.map((item, i) => <li key={i}>{item}</li>)}
                                </ul>
                            </div>
                        )}
                    </div>
                    <div className="space-y-3">
                        <h4 className="font-semibold text-brand-light">Peer B</h4>
                        <div className="flex items-center gap-2 mb-2">
                            <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                                report.sentimentAnalysis?.peerB?.sentiment === 'positive' ? 'bg-green-500/20 text-green-400' :
                                report.sentimentAnalysis?.peerB?.sentiment === 'negative' ? 'bg-red-500/20 text-red-400' :
                                'bg-gray-500/20 text-gray-400'
                            }`}>
                                {report.sentimentAnalysis?.peerB?.sentiment || 'neutral'}
                            </span>
                            <span className="text-sm text-brand-gray-400">{report.sentimentAnalysis?.peerB?.emotionalState || 'N/A'}</span>
                        </div>
                        {report.sentimentAnalysis?.peerB?.whatWentWell && report.sentimentAnalysis.peerB.whatWentWell.length > 0 && (
                            <div>
                                <p className="text-sm font-semibold text-green-400 mb-1">✓ What Went Well:</p>
                                <ul className="list-disc pl-5 space-y-1 text-sm">
                                    {report.sentimentAnalysis.peerB.whatWentWell.map((item, i) => <li key={i}>{item}</li>)}
                                </ul>
                            </div>
                        )}
                        {report.sentimentAnalysis?.peerB?.whatWentWrong && report.sentimentAnalysis.peerB.whatWentWrong.length > 0 && (
                            <div>
                                <p className="text-sm font-semibold text-orange-400 mb-1">⚠ Areas for Improvement:</p>
                                <ul className="list-disc pl-5 space-y-1 text-sm">
                                    {report.sentimentAnalysis.peerB.whatWentWrong.map((item, i) => <li key={i}>{item}</li>)}
                                </ul>
                            </div>
                        )}
                    </div>
                </div>
            </ReportCard>
            {report.riskWords && report.riskWords.detected && (
                <ReportCard title="Risk Detection" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>}>
                    <div className={`inline-block px-3 py-1 rounded-full text-xs font-semibold mb-3 ${
                        report.riskWords.severity === 'high' ? 'bg-red-500/20 text-red-400' :
                        report.riskWords.severity === 'medium' ? 'bg-orange-500/20 text-orange-400' :
                        'bg-yellow-500/20 text-yellow-400'
                    }`}>
                        Severity: {report.riskWords.severity || 'low'}
                    </div>
                    {report.riskWords.words && report.riskWords.words.length > 0 && (
                        <div className="mb-3">
                            <p className="text-sm font-semibold mb-1">Detected Words:</p>
                            <div className="flex flex-wrap gap-2">
                                {report.riskWords.words.map((word, i) => (
                                    <span key={i} className="px-2 py-1 bg-red-500/10 text-red-300 rounded text-xs">{word}</span>
                                ))}
                            </div>
                        </div>
                    )}
                    {report.riskWords.categories && report.riskWords.categories.length > 0 && (
                        <div>
                            <p className="text-sm font-semibold mb-1">Categories:</p>
                            <ul className="list-disc pl-5 space-y-1 text-sm">
                                {report.riskWords.categories.map((cat, i) => <li key={i}>{cat}</li>)}
                            </ul>
                        </div>
                    )}
                </ReportCard>
            )}
            {report.homeworkCompletion && (report.homeworkCompletion.peerA.totalCommitments > 0 || report.homeworkCompletion.peerB.totalCommitments > 0) && (
                <ReportCard title="Homework & Commitments" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>}>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <h4 className="font-semibold text-brand-light mb-2">Peer A Commitments</h4>
                            <p className="text-sm text-brand-gray-400 mb-3">
                                {report.homeworkCompletion.peerA.completed} / {report.homeworkCompletion.peerA.totalCommitments} completed
                            </p>
                            {report.homeworkCompletion.peerA.items && report.homeworkCompletion.peerA.items.length > 0 && (
                                <ul className="space-y-2">
                                    {report.homeworkCompletion.peerA.items.map((item, i) => (
                                        <li key={i} className="flex items-start gap-2">
                                            <span className={item.completed ? "text-green-400" : "text-gray-500"}>
                                                {item.completed ? "✓" : "○"}
                                            </span>
                                            <span className="text-sm">{item.commitment}</span>
                                        </li>
                                    ))}
                                </ul>
                            )}
                        </div>
                        <div>
                            <h4 className="font-semibold text-brand-light mb-2">Peer B Commitments</h4>
                            <p className="text-sm text-brand-gray-400 mb-3">
                                {report.homeworkCompletion.peerB.completed} / {report.homeworkCompletion.peerB.totalCommitments} completed
                            </p>
                            {report.homeworkCompletion.peerB.items && report.homeworkCompletion.peerB.items.length > 0 && (
                                <ul className="space-y-2">
                                    {report.homeworkCompletion.peerB.items.map((item, i) => (
                                        <li key={i} className="flex items-start gap-2">
                                            <span className={item.completed ? "text-green-400" : "text-gray-500"}>
                                                {item.completed ? "✓" : "○"}
                                            </span>
                                            <span className="text-sm">{item.commitment}</span>
                                        </li>
                                    ))}
                                </ul>
                            )}
                        </div>
                    </div>
                </ReportCard>
            )}
        </div>
        <div className="space-y-6">
            <ReportCard title="Talk-Time Balance" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a2 2 0 01-2-2V7a2 2 0 012-2h2m6-4a2 2 0 00-2-2H9a2 2 0 00-2 2v10a2 2 0 002 2h2" /></svg>}>
                <div className="w-full bg-brand-gray-700 rounded-full h-4 flex overflow-hidden">
                    <div className="bg-brand-primary" style={{ width: `${peerATalkPercentage}%` }}></div>
                    <div className="bg-brand-secondary" style={{ width: `${peerBTalkPercentage}%` }}></div>
                </div>
                <div className="flex justify-between mt-2 text-sm">
                    <span className="flex items-center"><div className="w-3 h-3 rounded-full bg-brand-primary mr-2"></div>Peer A: {peerATalkPercentage}%</span>
                    <span className="flex items-center"><div className="w-3 h-3 rounded-full bg-brand-secondary mr-2"></div>Peer B: {peerBTalkPercentage}%</span>
                </div>
                {report.talkTime.peerADetails && (
                    <div className="mt-4 pt-4 border-t border-brand-gray-700">
                        <p className="text-xs text-brand-gray-400 mb-1"><strong>Peer A:</strong> {report.talkTime.peerADetails}</p>
                    </div>
                )}
                {report.talkTime.peerBDetails && (
                    <div className="mt-2">
                        <p className="text-xs text-brand-gray-400 mb-1"><strong>Peer B:</strong> {report.talkTime.peerBDetails}</p>
                    </div>
                )}
            </ReportCard>
            {report.engagementScore && (
                <ReportCard title="Engagement Scores" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>}>
                    <div className="space-y-4">
                        <div>
                            <div className="flex justify-between mb-1">
                                <span className="text-sm">Peer A</span>
                                <span className="text-sm font-semibold">{report.engagementScore.peerA}/100</span>
                            </div>
                            <div className="w-full bg-brand-gray-700 rounded-full h-3">
                                <div className="bg-brand-primary h-3 rounded-full" style={{ width: `${report.engagementScore.peerA}%` }}></div>
                            </div>
                        </div>
                        <div>
                            <div className="flex justify-between mb-1">
                                <span className="text-sm">Peer B</span>
                                <span className="text-sm font-semibold">{report.engagementScore.peerB}/100</span>
                            </div>
                            <div className="w-full bg-brand-gray-700 rounded-full h-3">
                                <div className="bg-brand-secondary h-3 rounded-full" style={{ width: `${report.engagementScore.peerB}%` }}></div>
                            </div>
                        </div>
                        <div className="pt-2 border-t border-brand-gray-700">
                            <div className="flex justify-between mb-1">
                                <span className="text-sm font-semibold">Overall</span>
                                <span className="text-sm font-bold text-brand-primary">{report.engagementScore.overall}/100</span>
                            </div>
                            <div className="w-full bg-brand-gray-700 rounded-full h-4">
                                <div className="bg-gradient-to-r from-brand-primary to-brand-secondary h-4 rounded-full" style={{ width: `${report.engagementScore.overall}%` }}></div>
                            </div>
                        </div>
                    </div>
                </ReportCard>
            )}
             <ReportCard title="Mood & Engagement" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>}>
                <p>{report.moodAnalysis}</p>
             </ReportCard>
            <ReportCard title="Progress & Achievements" icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>}>
                <div className="flex justify-around text-center mb-4">
                    <div>
                        <div className="text-3xl font-bold text-white">{gamificationData.sessionCount}</div>
                        <div className="text-sm text-brand-gray-400">Sessions</div>
                    </div>
                    <div>
                        <div className="text-3xl font-bold text-white">{gamificationData.streak}</div>
                        <div className="text-sm text-brand-gray-400">Day Streak</div>
                    </div>
                </div>
                <div className="space-y-2 pt-4 border-t border-brand-gray-700">
                    <AchievementBadge label="First Session!" achieved={gamificationData.sessionCount >= 1} icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" strokeLinejoin="round" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" /></svg>} />
                    <AchievementBadge label="5 Sessions Strong" achieved={gamificationData.sessionCount >= 5} icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" strokeLinejoin="round" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.196-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.783-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" /></svg>} />
                    <AchievementBadge label="Consistency King" achieved={gamificationData.streak >= 3} icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"><path strokeLinecap="round" strokeLinejoin="round" d="M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7.014A8.003 8.003 0 0117.657 18.657z" /><path strokeLinecap="round" strokeLinejoin="round" d="M9.879 16.121A3 3 0 1014.12 11.88a3 3 0 00-4.242 4.242z" /></svg>} />
                </div>
            </ReportCard>
        </div>
      </div>
    </div>
  );
};

export default ReportView;